[tool.poetry]
name = "django"
version = "0.1.0"
description = ""
authors = ["sisi10856022 <10856022@ntub.edu.tw>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
